combine functions number_separate and oper_separate
laoching/python_basic pull request #8
Opened 2022-03-23 11:44 UTC by laoching

1+1을 입력하면
separate_formula 함수에서 [1, '+', 1]의 형태로 식을 분해합니다.

분해한 식을 calc 함수의 인자로 전달하여 계산 후 결과를 반환합니다.

2022-03-23 12:20 UTC, laoching commented
테스트 케이스랑 업로드 했습니다....만... 맞는지는 잘 모르겠습니다...

혹시 개발자들은 테스트 케이스를 작성해주는 스크립트도 만들곤 하는지요?

2022-03-30 12:06 UTC, laoching commented
하2요

2022-03-30 12:10 UTC, err0rless commented
테스트 케이스는 대부분 직접 작성합니다. 파이썬에서 효율적인 테스트 케이스 작성법은 @Kcrong 이분한테 조언을 구해보세요

2022-03-30 12:16 UTC, err0rless commented
파이썬에 조예가 깊지 않아서 코드에 대해 조언드릴게 많이 없네요, 조금 더 pythonic한 코드를 작성하도록 고려해보면 좋을 것 같아요.

또한 calc를 함수로 만들지 말고 class로 만들어서 class 설계도 해보면 좋을 것 같습니다.

2022-03-30 12:17 UTC, err0rless commented
그리고 커밋이 2개씩 중복되어 보이는데, squash commit으로 깔끔하게 만들어서 머지하면 좋을 것 같습니다.

2022-03-30 12:27 UTC, Kcrong requested changes
나날히 성장하는구만

2022-03-30 12:27 UTC, Kcrong commented on calc2.py
>              user_number.append(formula[:formula.index(i)])
이거 이런식으로 갈 수 있음

```python
for idx, ch in enumerate(formula):
    ....
    user_number.append(formula[:idx])
```

2022-03-30 12:27 UTC, Kcrong commented on calc2.py
>          if i in oper:
이렇게 쓰면 변수 덮어써지니까 변수명 분리해야함

2022-03-30 12:27 UTC, Kcrong commented on test_case.py
> +        self.assertEqual(calc2.calc([12, '*', 2, '+', 1]), 25)
굿 테스트는 이렇게 짜는거야 좀 더 구조를 개선해보자면


```python
class SeparateFormulaTest(TestCase):  # 테스트하려는 함수 별로 클래스 별도로 만드는게 좋음
    def test_plus_operator(self):  # 어떤 시나리오를 테스트할지 함수명으로 나타나도록
        ....

class CalcTest(TestCase):
    def test_....(self):
        ....
```

2022-03-30 12:27 UTC, Kcrong commented on calc2.py
> +def separate_formula(formula):
```suggestion
def parse_formula(formula):
```

2022-03-30 12:27 UTC, Kcrong commented on calc2.py
> +    return combine_formula
이 로직을 이해못했음.. 어떻게 개선해야할지 도움을 주고 싶은데 주석 추가 가능?

2022-03-30 12:42 UTC, laoching commented on calc2.py
>              user_number.append(formula[:formula.index(i)])
개추

2022-03-30 12:55 UTC, laoching commented on calc2.py
>          if i in oper:
formula = [1, '+', 2]
oper = ['+', '-', '*', '/']

식에서 연산자 빼내는 그런 부분입니다만.... 다른 방법이 있을까요?

2022-03-30 13:18 UTC, merged

2022-03-30 13:19 UTC, err0rless commented
커밋 메세지가 조금만 더 의미를 가졌으면 좋겠어요